version: '3'
services:
  database:
    image: postgres:15.0-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - starterkitdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGPORT=${DATABASE_PORT}
    container_name: ${DATABASE_HOST}
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - database
    image: starterkit.api
    container_name: starterkit.api
    command: python manage.py runserver 0.0.0.0:${PORT}
volumes:
  starterkitdb: {}