# Generated by Django 4.1.7 on 2023-03-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
    ]
