# Generated by Django 4.1.7 on 2023-04-25 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_usuario_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="apellido",
        ),
    ]
