# Generated by Django 4.1.7 on 2023-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_imap_imapusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="imapusuario",
            name="activo",
            field=models.BooleanField(default=False),
        ),
    ]
