# Generated by Django 4.1.7 on 2023-05-26 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_imapusuario_activo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioIMAP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servidor_usuario", models.CharField(max_length=255)),
                ("servidor_contrasena", models.CharField(max_length=128)),
                ("activo", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Usuarios / IMAP",
            },
        ),
        migrations.AlterModelOptions(
            name="imap",
            options={"verbose_name": "IMAP"},
        ),
        migrations.DeleteModel(
            name="IMAPUsuario",
        ),
        migrations.AddField(
            model_name="usuarioimap",
            name="servidor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="usuarios.imap"
            ),
        ),
        migrations.AddField(
            model_name="usuarioimap",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="IMAP",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
